version: '3.8'

services:

  db:
    image: postgres:13  # Use the DB image from Docker Hub
    container_name: db_container
    environment:
      POSTGRES_USER: ming_group
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dashboard_management
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ming_group", "-d", "dashboard_management"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  web:
    build:
      context: .
    container_name: web_container
    command: ./entrypoint.sh
    environment:
      DATABASE_URL: postgres://ming_group:1234@db:5432/dashboard_management
      DJANGO_SUPERUSER_USERNAME: ming_group_123
      DJANGO_SUPERUSER_PASSWORD: 1234
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - .:/app  # Mounts the current directory for development

  nginx:
    image: anirudhchawla889/ming_group_dashboard:nginx  # Use the Nginx image from Docker Hub
    container_name: nginx_container
    volumes:
      - ./nginx/dashboardManagement_no_passphrase.key:/etc/nginx/cert/dashboardManagement.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/etc/nginx/cert
      - ./static:/app/staticfiles
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
